{{- if .Values.jobs.radarrSync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "stalkerr.fullname" . }}-radarr-sync
  labels:
    {{- include "stalkerr.labels" . | nindent 4 }}
    app.kubernetes.io/component: cronjob-radarr-sync
spec:
  schedule: {{ .Values.jobs.radarrSync.schedule | quote }}
  concurrencyPolicy: {{ .Values.jobs.radarrSync.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.jobs.radarrSync.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.jobs.radarrSync.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "stalkerr.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: cronjob-radarr-sync
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "stalkerr.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: {{ .Values.jobs.radarrSync.restartPolicy }}
          containers:
            - name: radarr-sync
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: {{ include "stalkerr.image" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - ./stalkeer
                - radarr
                # - --config
                # - /etc/stalkerr/config.yaml
              env:
                - name: STALKERR_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "stalkerr.secretName" . }}
                      key: database-password
                - name: DATABASE_URL
                  value: {{ include "stalkerr.databaseUrl" . | quote }}
                - name: RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "stalkerr.secretName" . }}
                      key: radarr-api-key
              resources:
                {{- toYaml .Values.jobs.radarrSync.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  # mountPath: /etc/stalkerr/config.yaml
                  mountPath: /app/config.yaml
                  subPath: config.yaml
                  readOnly: true
                - name: m3u-storage
                  mountPath: /data/m3u
                - name: media-storage
                  mountPath: /media
                - name: temp-storage
                  mountPath: /tmp
          volumes:
            - name: config
              configMap:
                name: {{ include "stalkerr.configMapName" . }}
            - name: m3u-storage
              persistentVolumeClaim:
                claimName: {{ include "stalkerr.m3uPvcName" . }}
            - name: media-storage
              persistentVolumeClaim:
                claimName: {{ include "stalkerr.mediaPvcName" . }}
            - name: temp-storage
              emptyDir: {}
{{- end }}
