{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalkerr.fullname" . }}
  labels:
    {{- include "stalkerr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databasePassword }}
  database-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  {{- else if .Values.postgresql.enabled }}
  {{- if .Values.postgresql.auth.password }}
  database-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  database-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- else }}
  database-password: ""
  {{- end }}
  
  {{- if .Values.secrets.tmdbApiKey }}
  tmdb-api-key: {{ .Values.secrets.tmdbApiKey | b64enc | quote }}
  {{- else }}
  tmdb-api-key: ""
  {{- end }}
  
  {{- if .Values.secrets.radarrApiKey }}
  radarr-api-key: {{ .Values.secrets.radarrApiKey | b64enc | quote }}
  {{- else }}
  radarr-api-key: ""
  {{- end }}
  
  {{- if .Values.secrets.sonarrApiKey }}
  sonarr-api-key: {{ .Values.secrets.sonarrApiKey | b64enc | quote }}
  {{- else }}
  sonarr-api-key: ""
  {{- end }}
{{- end }}
