schema: spec-driven
created: "2026-09-06"
tags:
    type: frontend
    complexity: 3
    components:
        - backend
        - matcher
        - api
        - frontend
    _auto: true
    _tagged_at: "2026-09-21"
